import type { MenuCategoryResponse } from "@/features/menu/types";

export const testMenuCategories = [
  {
    id: 1,
    slug: "APP",
    displayName: "Appetisers",
    description: "Small plates to begin the meal.",
    displayOrder: 1,
    items: [
      {
        id: 101,
        slug: "A1",
        name: "Vegetarian Spring Rolls",
        description: "Crisp pastry rolls filled with cabbage, carrot, and mushroom.",
        price: 4.8,
        available: true,
        displayOrder: 1,
        imageUrl: null,
        tags: [{ id: 1, value: "vegetarian", color: "#16a34a" }],
      },
      {
        id: 102,
        slug: "A2",
        name: "Lemon Chicken",
        description: "Crispy chicken breast sliced with glossy lemon sauce.",
        price: 8.7,
        available: true,
        displayOrder: 2,
        imageUrl: null,
        tags: [{ id: 2, value: "popular", color: "#d97706" }],
      },
    ],
  },
  {
    id: 2,
    slug: "VEG",
    displayName: "Vegetarian and Tofu",
    description: "Vegetable, tofu, and mushroom dishes.",
    displayOrder: 2,
    items: [
      {
        id: 201,
        slug: "V1",
        name: "Vegetable Mapo Tofu",
        description: "Tofu and vegetables in a spicy Szechuan bean sauce.",
        price: 7.4,
        available: true,
        displayOrder: 1,
        imageUrl: null,
        tags: [
          { id: 1, value: "vegetarian", color: "#16a34a" },
          { id: 3, value: "spicy", color: "#dc2626" },
        ],
      },
    ],
  },
  {
    id: 3,
    slug: "RICE",
    displayName: "Rice",
    description: "Fried rice boxes and classic sides for sharing.",
    displayOrder: 3,
    items: [
      {
        id: 301,
        slug: "R1",
        name: "Egg Fried Rice",
        description: "Wok-fried rice with egg, peas, and spring onion.",
        price: 4.2,
        available: true,
        displayOrder: 1,
        imageUrl: null,
        tags: [{ id: 1, value: "vegetarian", color: "#16a34a" }],
      },
      {
        id: 302,
        slug: "R2",
        name: "Special Fried Rice",
        description: "Fried rice with chicken, roast pork, prawns, egg, and peas.",
        price: 7.8,
        available: true,
        displayOrder: 2,
        imageUrl: null,
        tags: [{ id: 2, value: "popular", color: "#d97706" }],
      },
    ],
  },
] satisfies MenuCategoryResponse[];
