import type { ShopProfileResponse } from "@/features/shop/types";

export const testShopProfile = {
  id: 1,
  slug: "firefly",
  displayName: "Firefly Restaurant",
  homeHeadline: "Fresh Chinese takeaway, cooked to order.",
  homeDescription:
    "Browse a generous menu of Chinese takeaway favourites, from crisp appetisers to wok-fried mains, rice, noodles, sides, and sauces.",
  contactIntro: "Find us locally for collection and takeaway service.",
  logoImageUrl: "https://images.example.invalid/shop/firefly-logo.png",
  heroImageUrl: "https://images.example.invalid/shop/firefly-hero.jpg",
  contactDetails: {
    phoneNumber: "020 7946 0100",
    addressLine1: "10 Firefly Lane",
    addressLine2: null,
    city: "London",
    region: null,
    postalCode: "SE1 1AA",
    country: "United Kingdom",
    mapUrl: "https://maps.example.invalid/firefly",
  },
  openingHours: [
    {
      id: 1,
      dayOfWeek: "Monday",
      opensAt: null,
      closesAt: null,
      isClosed: true,
      note: null,
    },
    {
      id: 2,
      dayOfWeek: "Tuesday",
      opensAt: "16:30:00",
      closesAt: "22:00:00",
      isClosed: false,
      note: null,
    },
    {
      id: 3,
      dayOfWeek: "Wednesday",
      opensAt: "16:30:00",
      closesAt: "22:00:00",
      isClosed: false,
      note: null,
    },
    {
      id: 4,
      dayOfWeek: "Thursday",
      opensAt: "16:30:00",
      closesAt: "22:00:00",
      isClosed: false,
      note: null,
    },
    {
      id: 5,
      dayOfWeek: "Friday",
      opensAt: "16:30:00",
      closesAt: "22:30:00",
      isClosed: false,
      note: null,
    },
    {
      id: 6,
      dayOfWeek: "Saturday",
      opensAt: "12:00:00",
      closesAt: "22:30:00",
      isClosed: false,
      note: null,
    },
    {
      id: 7,
      dayOfWeek: "Sunday",
      opensAt: "12:00:00",
      closesAt: "21:30:00",
      isClosed: false,
      note: null,
    },
  ],
} satisfies ShopProfileResponse;
